#!/bin/bash

# Builds ZIP archive for Windows in Docker

VERSION=4.4.0

CMAKE=/mxe/usr/bin/i686-w64-mingw32.static-cmake

CMD="export LANG=en_US.UTF-8 && \
     export LC_ALL=en_US.UTF-8 && \
     export PATH='$PATH':/mxe/usr/bin && \
     export CCACHE_DISABLE=1 && \
     cd /heimer && \
     rm -rf build-windows-zip && mkdir -p build-windows-zip && \
     cd build-windows-zip && ${CMAKE} -GNinja -DBUILD_WITH_QT6=ON -DPACKAGE_TYPE=ZIP .. && \
     ninja && \
     mkdir zip && cd zip && \
     cp -v ../AUTHORS . && \
     cp -v ../CHANGELOG . && \
     cp -v ../COPYING . && \
     cp -v ../README.md . && \
     cp -v ../heimer.exe . && \
     zip -r heimer-${VERSION}-win32.zip *"

if [ -f /.dockerenv ]; then
    echo "Script inside Docker"
    bash -c "${CMD}"
else
    echo "Script outside Docker"
    docker run --user $(id -u):$(id -g) -t -v $(pwd):/heimer juzzlin/mxe-qt6-22.04:latest bash -c "${CMD}"
fi

