#!/bin/bash

# Builds NSIS installer for Windows in Docker

MAKENSIS=/mxe/usr/bin/i686-w64-mingw32.static-makensis
CMAKE=/mxe/usr/bin/i686-w64-mingw32.static-cmake

CMD="export LANG=en_US.UTF-8 && \
     export LC_ALL=en_US.UTF-8 && \
     export PATH='$PATH':/mxe/usr/bin && \
     cd /heimer && \
     rm -rf build-windows-nsis && mkdir -p build-windows-nsis && \
     cd build-windows-nsis && ${CMAKE} -DPACKAGE_TYPE=NSIS .. && \
     make -j4 && \
     cp -v ../packaging/windows/heimer.nsi . && \
     ${MAKENSIS} heimer.nsi"

if [ -f /.dockerenv ]; then
    echo "Script inside Docker"
    bash -c "${CMD}"
else
    echo "Script outside Docker"
    docker run --user $(id -u):$(id -g) -t -v $(pwd):/heimer juzzlin/mxe-qt5-20.04:latest bash -c "${CMD}"
fi

