FROM ubuntu:18.04

RUN apt update && apt upgrade -y

RUN apt install build-essential cmake qt5-default -y

RUN apt install qttools5-dev-tools -y

RUN apt install qttools5-dev -y

RUN apt install libopenal-dev -y

RUN apt install libvorbis-dev -y

